version: "3"
services:

  mysql:
    build: ./docker/db
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 63307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    container_name: "docker_app_mysql"

  redis:
    image: redis:latest
    volumes:
      - ./data/redis:/data
    ports:
      - 6377:6379
    command: redis-server --appendonly yes
    container_name: "docker_app_redis"

  php:
    build: ./docker/app
    links:
      - mysql
      - redis
    volumes:
      - .:/var/data
      - ./rs_api:/srv/projects/rs_api
      - ./data/logs/php:/var/log/php-fpm
    working_dir: /var/data
    container_name: "docker_app_php"

  nginx:
    build: ./docker/web
    ports:
      - "8084:80"
      - "8085:8085"
    links:
      - php
    volumes:
      - ./docker/web/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/web/conf/web.conf:/etc/nginx/conf.d/web.conf
      - ./docker/web/conf/rs_api.conf:/etc/nginx/conf.d/rs_api.conf
      - .:/var/data
      - ./rs_api:/srv/projects/rs_api
      - ./data/logs/nginx:/var/log/nginx
    container_name: "docker_app_nginx"

  nodejs:
    image: node:11
    container_name: "docker_app_nodejs"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/var/data:cached
    working_dir: /var/data
    expose:
      - "8085"
    tty: true


